[en]
  languageName = "English"
  languageCode = "en"
  weight = 2
  title = "Chirpy"
  [en.params]
    tagline = "A text-focused blog theme"

[ko-KR]
  languageName = "한국어"
  languageCode = "ko-KR"
  weight = 1
  title = "Chirpy"
  [ko-KR.params]
    tagline = "텍스트기반 블로그 테마"
