toc = true
avatar = "img/commons/avatar.jpg"
author = "freein"

[assets]
  self_host = false

[social]
  name = "urfreein"
  url = "https://github.com/urfreein"

[[social.links]]
  type = "github"
  id = "urfreein"  # 或直接使用 url = "https://github.com/yourusername"
  icon = "fab fa-github"

[[social.links]]
  type = "twitter"
  id = "youkes"
  icon = "fab fa-twitter"

[[social.links]]
  type = "email"
  id = "your.email@example.com"  # 会被自动分割处理
  icon = "fas fa-envelope"

[[social.links]]
  type = "rss"
  icon = "fas fa-rss"
  noblank = true  # 不在新窗口打开
