# .github/workflows/hugo-deploy.yml 파일 내용
name: Deploy Hugo site to Pages

on:
  push:
    branches: ["master"] # master 브랜치에 푸시가 발생할 때 실행
  workflow_dispatch: # 수동 실행을 허용

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # 테마를 서브모듈로 사용했다면 필수 (모듈 사용 시에도 안전)
          fetch-depth: 0    # 전체 Git 기록을 가져옴

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3 # Hugo 설정 액션
        with:
          hugo-version: 'latest'
          extended: true # Hugo Extended 버전 사용
          **compiler: "dart-sass"** # Chirpy 테마 빌드 시 Dart Sass 의존성 해결

      - name: Build Hugo
        # public 폴더에 정적 파일을 생성합니다.
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # 빌드 결과물(정적 파일)이 있는 폴더

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # build Job이 성공해야 실행
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # GitHub Pages에 배포하는 공식 액션
